### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by kangfenmao** [jpush/jverification-react-native#18]
# 版本号

"jpush-react-native": "^2.8.0",
"jverification-react-native": "^2.3.1" -> "jverification-react-native": "^2.4.3"

# 错误信息

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/arm64-v8a/libjcore234.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

    at makeError (/node_modules/execa/index.js:174:9)
    at /node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
```

# 问题原因

项目包含了 jcore 的 lib，删除 lib 目录中 jcore 文件可以正常解决问题

**Comment by yz1311** [comment]
这问题这么长时间了，居然官方一个回复都没有，难怪star这么少

**Comment by JohnsonChow** [comment]
是否由多文件引入重复问题兄弟
